name: PhpCsFixer

on:
  workflow_dispatch:

  pull_request:
    types: [opened, reopened]
    paths: ["**.php"]
    branches: [master] # PR先のブランチ

jobs:
  php_cs_fixer:
    runs-on: ubuntu-latest
    steps:
      # 1. 実行環境準備
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
          fetch-depth: 0
      - name: Fetch
        shell: bash -xe {0}
        run: |
          git fetch --depth 1 origin ${{github.head_ref}}
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.2"
          tools: php-cs-fixer
      # 2. 構文チェック
      # （厳密な静的解析はpre-commitで確認する. ここではあくまで整形可能かどうかの確認なので、ここで失敗した場合に開発者側で何かするという必要はない.）
      - name: check syntax error
        shell: bash -xe {0}
        run: |
          if git diff origin/master...HEAD --name-only --diff-filter=ACMR *.php | \
          xargs -n1 -P4 php -l | \
          grep -v "No syntax errors detected"; then exit 1; fi
      # 3. php-cs-fixer実行
      - name: execute php-cs-fixer
        shell: bash -xe {0}
        run: |
          git diff origin/master...HEAD --name-only --diff-filter=ACMR *.php | \
          grep -v '^manage/views' | \
          xargs -n1 -P4 php-cs-fixer fix --using-cache=no
      # 4. commit
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: pxp-cs-fixer by Github Actions
