name: PhpCsFixer

on:
  push:
    paths: ['**.php']
  pull_request:
    paths: ['**.php']
    types: [opened]

  # フェーズ１
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches: [release/master]
  #   types: [opened, reopened, synchronize]

  # フェーズ２
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches: [staging/master]
  #   types: [opened, reopened]

  # PRレビュー用
  # pull_request:
  #   branches-ignore:
  #     - '**'

jobs:
  php_cs_fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
          fetch-depth: 0
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: php-cs-fixer
      - name: check syntax error
        run: |
          if git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} --name-only --diff-filter=ACMR *.php | \
          xargs -n1 -P4 php -l | \
          grep -v "No syntax errors detected"; then exit 1; fi
      - name: execute php-cs-fixer
        run: |
          git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} --name-only --diff-filter=ACMR *.php | \
          grep -v '^manage/views' | \
          xargs -n1 -P4 php-cs-fixer fix --using-cache=no
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: pxp-cs-fixer by Github Actions
