name: PhpCsFixer

# on:
#   push:
#     branches: [staging/master]
#   pull_request: # フェーズ3ではプルリク作成時に実行
#     types: [opened]

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  php_cs_fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: php-cs-fixer
      - name: check syntax error
        run: |
          if git diff --name-only --diff-filter=ACMR origin/master..HEAD -- '*.php' | \
          xargs -n1 -P4 php -l | \
          grep -v "No syntax errors detected"; then exit 1; fi
      - name: execute php-cs-fixer
        run: |
          git diff --name-only --diff-filter=ACMR origin/master..HEAD *.php | \
          grep -v '^manage/views' | \
          xargs -n1 -r -P4 php-cs-fixer fix --using-cache=no
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: pxp-cs-fixer by Github Actions
